name: Publish docs

on: 
  workflow_dispatch:  # manual
  branches: [ main ]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python
      with:
        python-version: "3.10"
    
    - name: Install package and dependencies
      run: |
        python3 -m pip install -e .[docs]
    
    - name: Build docs
      run: |
        sphinx-build docs_src docs -b dirhtml
    
    - name: Bypass Jekyll
      run: |
        echo "" > docs/.nojekyll

    - name: Commit
      run: |
        git add --all
        git commit --all -m "sys: Build documentation"
    
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
